### ISSUE TITLE
heachi-core-auth Login, Reigster 기능

### ISSUE THREAD

**Issue by ghdcksgml1** [ghdcksgml1/heachi-backend#8]
- [ ] LoginController
- [ ] ReigsterController

**Comment by jusung-c** [comment]
@ghdcksgml1 

로그인 구현을 해보려고 했는데요..!
일단은 OAuthServiceTest 테스트 통과하도록 OAuth 로그인 인증 후에 DB에 없다면 등록해줬는데요

@DisplayName("유저 플랫폼과 코드를 넘기면, 로그인이 성공하고, JWT 토큰이 정상적으로 발행된다.")
@DisplayName("로그인이 완료된 사용자의 jwt 토큰에는 알맞은 Claims가 들어가있어야 한다.")

이 두 테스트는 통과할 줄 알았는데 다 실패하네요.. 혹시 놓치고 있는 게 있을까요?

**Comment by ghdcksgml1** [comment]
> JWT Claims에 들어가야하는 내용

```javascript
{
    "role": "USER", // 해당 유저의 UserRole
    "name": "홍찬희", // 해당 유저의 Name
    "profileImageUrl": "http://vasadfdasfsdf.com" // 해당 유저의 프로필 사진 URL
}
```

Map의 키를 확인해주세요 :)

**Comment by ghdcksgml1** [comment]
PR 올리시면 리뷰해드리겠습니다~~
